CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    name varchar(250) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS compilations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar NOT NULL,
    pinned boolean,
    CONSTRAINT uq_compilation_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(120) NOT NULL,
    annotation varchar(2000) NOT NULL,
    category_id bigint NOT NULL REFERENCES categories (id),
    created_on timestamp NOT NULL,
    description varchar(7000) NOT NULL,
    event_date timestamp NOT NULL,
    initiator_id bigint NOT NULL REFERENCES users (id),
    latitude float NOT NULL,
    longitude float NOT NULL,
    paid boolean NOT NULL,
    participant_limit integer NOT NULL,
    published_on timestamp,
    request_moderation boolean NOT NULL,
    comment_moderation boolean NOT NULL,
    state varchar NOT NULL,
    confirmed_requests integer
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id bigint NOT NULL REFERENCES compilations (id),
    event_id bigint NOT NULL REFERENCES events (id),
    CONSTRAINT uq_compilation_event UNIQUE (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES events (id),
    requester_id bigint NOT NULL REFERENCES users (id),
    status varchar(9) NOT NULL,
    created timestamp NOT NULL,
    CONSTRAINT uq_request UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES events (id),
    author_id bigint NOT NULL REFERENCES users (id),
    text varchar(1000) NOT NULL,
    status varchar(9) NOT NULL,
    created timestamp NOT NULL,
    edited timestamp
)